# Generated by Django 4.1.1 on 2022-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('title', models.IntegerField()),
                ('description', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
