# Generated by Django 4.1.1 on 2022-09-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchGithub', '0002_alter_candidate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='userLink',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
