# Generated by Django 4.1.1 on 2022-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchGithub', '0003_candidate_userlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
