# Generated by Django 4.1.1 on 2022-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchGithub', '0005_alter_candidate_country_alter_candidate_userlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
